name = "BackwordsDiffLibrary"
uuid = "904dbfbe-6d3e-483a-a8cb-66278886ffc3"
authors = ["Karaś Kacper <karas.kacper@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
